src/cn/jsprun/foreg/vo/archiver/Foot_inc.java
package cn.jsprun.foreg.vo.archiver;
import java.util.Map;
public class Foot_inc {
	private Map<String,String> fullversion = null;
	private String footerbanner1 = null;
	private String footerbanner2 = null;
	private String footerbanner3 = null;
	private String version = null; 
	public Map<String, String> getFullversion() {
		return fullversion;
	}
	public void setFullversion(Map<String, String> fullversion) {
		this.fullversion = fullversion;
	}
	public String getFooterbanner1() {
		return footerbanner1;
	}
	public void setFooterbanner1(String footerbanner1) {
		this.footerbanner1 = footerbanner1;
	}
	public String getFooterbanner2() {
		return footerbanner2;
	}
	public void setFooterbanner2(String footerbanner2) {
		this.footerbanner2 = footerbanner2;
	}
	public String getFooterbanner3() {
		return footerbanner3;
	}
	public void setFooterbanner3(String footerbanner3) {
		this.footerbanner3 = footerbanner3;
	}
	public String getVersion() {
		return version;
	}
	public void setVersion(String version) {
		this.version = version;
	}
	public String getTitle() {
		if(fullversion==null){
			return "";
		}else{
			return fullversion.get("title");
		}
	}
	public String getLink() {
		if(fullversion==null){
			return "";
		}else{
			return fullversion.get("link");
		}
	}
}

src/cn/jsprun/foreg/vo/archiver/Forum.java
package cn.jsprun.foreg.vo.archiver;
public class Forum {
	private String fid = null;
	private String name = null;
	public String getFid() {
		return fid;
	}
	public void setFid(String fid) {
		this.fid = fid;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
}

src/cn/jsprun/foreg/vo/archiver/Forum_inc.java
package cn.jsprun.foreg.vo.archiver;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
public class Forum_inc extends WithHeaderAndFoot {
	private String redirect = null;
	private boolean refuse = false; 
	private String bbname = null; 
	private boolean navsub = false;
	private String qm = null;
	private Forum currentForum = null;
	private Forum superForum = null;
	private Integer start = null; 
	private List<Thread> threadList = new ArrayList<Thread>();
	private Map<String,String> fullversion = null;
	private Multi_inc multi_inc = null;
	public static class Thread{
		private String tid = null;
		private String subject = null;
		private String replies = null;
		public String getTid() {
			return tid;
		}
		public void setTid(String tid) {
			this.tid = tid;
		}
		public String getSubject() {
			return subject;
		}
		public void setSubject(String subject) {
			this.subject = subject;
		}
		public String getReplies() {
			return replies;
		}
		public void setReplies(String replies) {
			this.replies = replies;
		}
	}
	public Thread getThread(){
		return new Thread();
	}
	public boolean getRefuse() {
		return refuse;
	}
	public void setRefuse(boolean refuse) {
		this.refuse = refuse;
	}
	public String getBbname() {
		return bbname;
	}
	public void setBbname(String bbname) {
		this.bbname = bbname;
	}
	public boolean getNavsub() {
		return navsub;
	}
	public void setNavsub(boolean navsub) {
		this.navsub = navsub;
	}
	public String getQm() {
		return qm;
	}
	public void setQm(String qm) {
		this.qm = qm;
	}
	public Integer getStart() {
		return start + 1;
	}
	public void setStart(Integer start) {
		this.start = start;
	}
	public List<Thread> getThreadList() {
		return threadList;
	}
	public String getTitle() {
		if(fullversion==null){
			return "";
		}else{
			return fullversion.get("title");
		}
	}
	public String getLink() {
		if(fullversion==null){
			return "";
		}else{
			return fullversion.get("link");
		}
	}
	public void setFullversion(Map<String, String> fullversion) {
		this.fullversion = fullversion;
	}
	public String getRedirect() {
		return redirect;
	}
	public void setRedirect(String redirect) {
		this.redirect = redirect;
	}
	public void setCurrentForum(Forum currentForum) {
		this.currentForum = currentForum;
	}
	public void setSuperForum(Forum superForum) {
		this.superForum = superForum;
	}
	public Forum getCurrentForum() {
		return currentForum;
	}
	public Forum getSuperForum() {
		return superForum;
	}
	public Multi_inc getMulti_inc() {
		return multi_inc;
	}
	public void setMulti_inc(Multi_inc multi_inc) {
		this.multi_inc = multi_inc;
	}
}

src/cn/jsprun/foreg/vo/archiver/Header_inc.java
package cn.jsprun.foreg.vo.archiver;
import java.util.Map;
public class Header_inc {
	private String boardurl = null; 
	private Map<String,String> settingMap = null;
	private String navtitle = null;
	private String meta_contentadd = null;
	private String headerbanner = null;
	public String getNavtitle() {
		return navtitle;
	}
	public void setNavtitle(String navtitle) {
		this.navtitle = navtitle;
	}
	public String getBbname() {
		if(settingMap!=null){
			return settingMap.get("bbname");
		}else{
			return "";
		}
	}
	public String getSeotitle() {
		if(settingMap!=null){
			return settingMap.get("seotitle");
		}else{
			return "";
		}
	}
	public String getSeohead() {
		if(settingMap!=null){
			return settingMap.get("seohead");
		}else{
			return "";
		}
	}
	public String getSeokeywords() {
		if(settingMap!=null){
			return settingMap.get("seokeywords");
		}else{
			return "";
		}
	}
	public String getMeta_contentadd() {
		return meta_contentadd;
	}
	public void setMeta_contentadd(String meta_contentadd) {
		this.meta_contentadd = meta_contentadd;
	}
	public String getVersion() {
		if(settingMap!=null){
			return settingMap.get("version");
		}else{
			return "";
		}
	}
	public String getStyleid() {
		if(settingMap!=null){
			return settingMap.get("styleid");
		}else{
			return "";
		}
	}
	public boolean getHaveHeaderbanner() {
		return headerbanner!=null&&!headerbanner.equals("");
	}
	public String getHeaderbanner() {
		return headerbanner;
	}
	public void setHeaderbanner(String headerbanner) {
		this.headerbanner = headerbanner;
	}
	public String getBoardurl() {
		return boardurl;
	}
	public void setBoardurl(String boardurl) {
		this.boardurl = boardurl;
	}
	public void setSettingMap(Map<String, String> settingMap) {
		this.settingMap = settingMap;
	}
	public String getSeodescription(){
		if(settingMap!=null){
			return settingMap.get("seodescription");
		}else{
			return "";
		}
	}
}

src/cn/jsprun/foreg/vo/archiver/Index_inc.java
package cn.jsprun.foreg.vo.archiver;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
public class Index_inc extends WithHeaderAndFoot{
	private Map<String,String> settingMap = null;
	private Map<String,String> fullversion = null;
	private List<Forums> groupList = new LinkedList<Forums>();
	private String qm = null;
	public String getQm() {
		return qm;
	}
	public void setQm(String qm) {
		this.qm = qm;
	}
	public String getTitle() {
		if(fullversion==null){
			return "";
		}else{
			return fullversion.get("title");
		}
	}
	public String getLink() {
		if(fullversion==null){
			return "";
		}else{
			return fullversion.get("link");
		}
	}
	public String getBbname() {
		if(settingMap!=null){
			return settingMap.get("bbname");
		}else{
			return "";
		}
	}
	public void setSettingMap(Map<String, String> settingMap) {
		this.settingMap = settingMap;
	}
	public void setFullversion(Map<String, String> fullversion) {
		this.fullversion = fullversion;
	}
	public static class Forums{
		private String name = null;
		private String fid = null;
		private List<Forums> forumList = null;
		public String getName() {
			return name;
		}
		public void setName(String name) {
			this.name = name;
		}
		public String getFid() {
			return fid;
		}
		public void setFid(String fid) {
			this.fid = fid;
		}
		public List<Forums> getForumList() {
			if(forumList==null){
				forumList = new LinkedList<Forums>();
			}
			return forumList;
		}
	}
	public Forums getForums(){
		return new Forums();
	}
	public List<Forums> getGroupList() {
		return groupList;
	}
}

src/cn/jsprun/foreg/vo/archiver/Multi_inc.java
package cn.jsprun.foreg.vo.archiver;
public class Multi_inc {
	private Integer pageStart = null;	
	private Integer pageEnd = null;	
	private String link = null;	
	private Integer nowPage = null;	
	private Integer pages = null; 
	private Integer showPageNum = null; 
	private Integer total = null; 
	private Integer perpage = null; 
	public Multi_inc(Integer nowPage,Integer showPageNum,
			Integer total,Integer perpage,String link){
		this.nowPage = nowPage;
		this.showPageNum = showPageNum;
		this.total = total;
		this.perpage = perpage;
		this.link = link;
		init();
	}
	public String getLink() {
		return link;
	}
	public void setLink(String link) {
		this.link = link;
	}
	public Integer getNowPage() {
		return nowPage;
	}
	public void setNowPage(Integer nowPage) {
		this.nowPage = nowPage;
	}
	public Integer getPageStart() {
		return pageStart;
	}
	public Integer getPageEnd() {
		return pageEnd;
	}
	public void setPerpage(Integer perpage) {
		this.perpage = perpage;
	}
	public void setShowPageNum(Integer showPageNum) {
		this.showPageNum = showPageNum;
	}
	public void setTotal(Integer total) {
		this.total = total;
	}
	public boolean getMulti() {
		return pages > 1;
	}
	private void init(){
		pages = (int)(Math.ceil((double)total / perpage));
		pageStart = nowPage - showPageNum < 1 ? 1 : nowPage - showPageNum;
		pageEnd = nowPage + showPageNum >= pages ? pages : nowPage + showPageNum -1;
	}
}

src/cn/jsprun/foreg/vo/archiver/Thread_inc.java
package cn.jsprun.foreg.vo.archiver;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
public class Thread_inc extends WithHeaderAndFoot {
	private boolean refuse = false; 
	private String bbname = null;
	private boolean navsub = false;
	private String qm = null;
	private Forum superForum = null;
	private Forum currentForum = null;
	private String threadSubject = null;
	private List<Posts> postsList = new ArrayList<Posts>();
	private Map<String,String> fullversion = null;
	private Multi_inc multi_inc = null;
	public static class Posts{
		private String author = null;
		private String dateline = null;
		private String message = null;
		public String getAuthor() {
			return author;
		}
		public void setAuthor(String author) {
			this.author = author;
		}
		public String getDateline() {
			return dateline;
		}
		public void setDateline(String dateline) {
			this.dateline = dateline;
		}
		public String getMessage() {
			return message;
		}
		public void setMessage(String message) {
			this.message = message;
		}
	}
	public Posts getPosts(){
		return new Posts();
	}
	public boolean getRefuse() {
		return refuse;
	}
	public void setRefuse(boolean refuse) {
		this.refuse = refuse;
	}
	public String getBbname() {
		return bbname;
	}
	public void setBbname(String bbname) {
		this.bbname = bbname;
	}
	public boolean getNavsub() {
		return navsub;
	}
	public void setNavsub(boolean navsub) {
		this.navsub = navsub;
	}
	public String getQm() {
		return qm;
	}
	public void setQm(String qm) {
		this.qm = qm;
	}
	public Forum getSuperForum() {
		return superForum;
	}
	public void setSuperForum(Forum superForum) {
		this.superForum = superForum;
	}
	public Forum getCurrentForum() {
		return currentForum;
	}
	public void setCurrentForum(Forum currentForum) {
		this.currentForum = currentForum;
	}
	public String getThreadSubject() {
		return threadSubject;
	}
	public void setThreadSubject(String threadSubject) {
		this.threadSubject = threadSubject;
	}
	public List<Posts> getPostsList() {
		return postsList;
	}
	public String getLink() {
		if(fullversion!=null){
			return fullversion.get("link");
		}
		return "";
	}
	public String getTitle() {
		if(fullversion!=null){
			return fullversion.get("title");
		}
		return "";
	}
	public void setFullversion(Map<String, String> fullversion) {
		this.fullversion = fullversion;
	}
	public Multi_inc getMulti_inc() {
		return multi_inc;
	}
	public void setMulti_inc(Multi_inc multi_inc) {
		this.multi_inc = multi_inc;
	}
}

src/cn/jsprun/foreg/vo/archiver/WithHeaderAndFoot.java
package cn.jsprun.foreg.vo.archiver;
public class WithHeaderAndFoot {
	private Header_inc header = null;
	private Foot_inc footer = null;
	public Header_inc getHeader() {
		return header;
	}
	public void setHeader(Header_inc header) {
		this.header = header;
	}
	public Foot_inc getFooter() {
		return footer;
	}
	public void setFooter(Foot_inc footer) {
		this.footer = footer;
	}
}

WebRoot/archiver/include/foot_inc.jsp
<%@ page language="java" pageEncoding="UTF-8"%>
<%@ taglib uri="http://struts.apache.org/tags-bean" prefix="bean"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<div class="archiver_fullversion"><bean:message key="full_version" />: <strong><a href="${valueObject.footer.link }" target="_blank">${valueObject.footer.title }</a></strong></div>
</div>
<c:if test="${!empty valueObject.footer.footerbanner1}"><div class="archiver_banner">${valueObject.footer.footerbanner1 }</div></c:if>
<c:if test="${!empty valueObject.footer.footerbanner2}"><div class="archiver_banner">${valueObject.footer.footerbanner2 }</div></c:if>
<c:if test="${!empty valueObject.footer.footerbanner3}"><div class="archiver_banner">${valueObject.footer.footerbanner3 }</div></c:if>
<p id="copyright">Powered by <strong><a href="http://www.jsprun.net" target="_blank">JspRun! Archiver</a></strong> <em>${valueObject.footer.version }</em>&nbsp; &copy; 2007-2011 <a href="http://www.jsprun.com" target="_blank">JspRun! Inc.</a><br /><br /></p>
</body>
</html>

WebRoot/archiver/include/forum_inc.jsp
<%@ page language="java" pageEncoding="UTF-8"%>
<%@ taglib uri="http://struts.apache.org/tags-bean" prefix="bean"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@include file="header_inc.jsp"%>
<c:choose>
	<c:when test="${valueObject.refuse}">
		<div id="nav"><a href="archiver/">${valueObject.bbname }</a></div>
		<div><bean:message key="forum_nonexistence_archiver" /></div>
	</c:when>
	<c:otherwise>
		<div id="nav">
			<a href="archiver/">${valueObject.bbname}</a> &raquo;
			<c:if test="${valueObject.navsub }"><a href="archiver/${valueObject.qm}fid-${valueObject.superForum.fid}.html">${valueObject.superForum.name}</a> &raquo;</c:if>
			<a href="archiver/${valueObject.qm}fid-${valueObject.currentForum.fid}.html">${valueObject.currentForum.name}</a>
		</div>
		<h1><a href="${valueObject.link}" target="_blank"><bean:message key="full_version" />: ${valueObject.title}</a></h1>
		<ul class="archiver_threadlist" type="1" start="${valueObject.start}">
			<c:forEach items="${valueObject.threadList}" var="thread">
				<li><a href="archiver/${valueObject.qm}tid-${thread.tid }.html">${thread.subject}</a> <em>(${thread.replies } <bean:message key="replies" />)</em></li>
			</c:forEach>
		</ul>
		<div class="archiver_pages">
			<c:if test="${valueObject.multi_inc.multi}"><%@ include file="multi.jsp"%></c:if>
		</div>
	</c:otherwise>
</c:choose>
<%@include file="foot_inc.jsp"%>

WebRoot/archiver/include/header_inc.jsp
<%@ page language="java" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<base href="${valueObject.header.boardurl }" />
<title>${valueObject.header.navtitle} ${valueObject.header.bbname} ${valueObject.header.seotitle} - Powered by JspRun! Archiver</title>
${valueObject.header.seohead}
<meta name="keywords" content="JspRun!,JspRun,forums,bulletin board,${valueObject.header.seokeywords }" />
<meta name="description" content="${valueObject.header.meta_contentadd } ${valueObject.header.bbname } ${valueObject.header.seodescription }- JspRun! Archiver" />
<meta name="generator" content="JspRun! Archiver ${valueObject.header.version }" />
<meta name="author" content="JspRun! Team & JspRun UI Team" />
<meta name="copyright" content="2007-2011 JspRun Inc." />
<link rel="stylesheet" type="text/css" href="forumdata/cache/style_${valueObject.header.styleid }.css" />
<link rel="SHORTCUT ICON" href="../favicon.ico" />
<style type="text/css">


</style>
</head>
<body class="archiver">
<c:if test="${valueObject.header.haveHeaderbanner}"><div class="archiver_banner">${valueObject.header.headerbanner}</div></c:if>
<div class="wrap">

WebRoot/archiver/include/index_inc.jsp
<%@ page language="java" pageEncoding="UTF-8"%>
<%@ taglib uri="http://struts.apache.org/tags-bean" prefix="bean"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@include file="header_inc.jsp"%>
<div id="nav"><a href="archiver/">${valueObject.bbname}</a></div>
<h1><a href="${valueObject.link}" target="_blank"><bean:message key="full_version" />: ${valueObject.title}</a></h1>
<ul class="archiver_forumlist">
	<c:forEach items="${valueObject.groupList}" var="group">
		<li>
			<h3>${group.name}</h3>
			<ul><c:forEach items="${group.forumList}" var="forum">
				<li>
					<a href="archiver/${valueObject.qm}fid-${forum.fid}.html">${forum.name}</a>
					<ul><c:forEach items="${forum.forumList}" var="subForum"><li><a href="archiver/${valueObject.qm}fid-${subForum.fid }.html">${subForum.name}</a></li></c:forEach></ul>
				</li>
			</c:forEach></ul>
		</li>
	</c:forEach>
</ul>
<%@include file="foot_inc.jsp"%>

WebRoot/archiver/include/multi.jsp
<%@ page language="java" pageEncoding="UTF-8"%>
<%@ taglib uri="http://struts.apache.org/tags-bean" prefix="bean"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<bean:message key="page" />:
<c:forEach begin="${valueObject.multi_inc.pageStart}" end="${valueObject.multi_inc.pageEnd}" var="pageNum">
	<c:choose>
		<c:when test="${pageNum==valueObject.multi_inc.nowPage}"><strong>[${pageNum}]</strong></c:when>
		<c:otherwise><a href="archiver/${valueObject.multi_inc.link}-page-${pageNum}.html">${pageNum}</a></c:otherwise>
	</c:choose>
</c:forEach>

WebRoot/archiver/include/thread_inc.jsp
<%@ page language="java" pageEncoding="UTF-8"%>
<%@ taglib uri="http://struts.apache.org/tags-bean" prefix="bean"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@include file="header_inc.jsp"%>
<c:choose>
	<c:when test="${valueObject.refuse}">
		<div id="nav"><a href="archiver/">${valueObject.bbname}</a></div><br />
		<div class="simpletable smalltxt"><div class="subtable altbg2"><br /><bean:message key="thread_nonexistence_inc" /><br /><br /></div></div>
	</c:when>
	<c:otherwise>
		<div id="nav">
			<a href="archiver/">${valueObject.bbname}</a> &raquo;
			<c:if test="${valueObject.navsub}"><a href="archiver/${valueObject.qm}fid-${valueObject.superForum.fid }.html">${valueObject.superForum.name}</a> <b>&raquo;</b></c:if>
			<a href="archiver/${valueObject.qm}fid-${valueObject.currentForum.fid}.html">${valueObject.currentForum.name}</a> &raquo; ${valueObject.threadSubject}
		</div>
		<h1><a href="${valueObject.link}" target="_blank"><bean:message key="full_version" />: ${valueObject.title}</a></h1>
		<c:forEach items="${valueObject.postsList}" var="post">
			<div class="archiver_post">
				<p><cite>${post.author}</cite> ${post.dateline}</p>
				<div class="archiver_postbody">${post.message}</div>
			</div>
		</c:forEach>
		<div class="archiver_pages">
			<c:if test="${valueObject.multi_inc.multi}"><%@ include file="multi.jsp"%></c:if>
		</div>
	</c:otherwise>
</c:choose>
<%@include file="foot_inc.jsp"%>